### ISSUE TITLE
Allow online (https) CSS in `markdown-pdf.styles`

### ISSUE THREAD

**Issue by vimtaai** [yzane/vscode-markdown-pdf#67]
It would be nice to be able to include online CSS without the need to have a local copy.

```json
"markdown-pdf.styles": [
  "https://unpkg.com/mdss"
]
```

Sadly this is not working.

**Comment by yzane** [comment]
```json
"markdown-pdf.styles": [
  "https://unpkg.com/mdss"
]
```
The CSS is applied correctly in JPG and PNG, but there is a problem with the PDF. 
For now, I will release it as a known issue.

**Comment by Haenkos** [comment]
A missing semicolon in the '@media print' rule of the linked stylesheet at [https://unpkg.com/mdss](https://unpkg.com/mdss) is causing problems with PDF-export (paragraph text not showing). At the first instance of the '@media print' rule, a semicolon is missing after the 'body{color:#000}' attribute. Adding a semicolon fixes the problem of paragraph text not showing. See also issue #240 .

**Comment by vimtaai** [comment]
> A missing semicolon in the '@media print' rule of the linked stylesheet at https://unpkg.com/mdss is causing problems with PDF-export (paragraph text not showing). At the first instance of the '@media print' rule, a semicolon is missing after the 'body{color:#000}' attribute. Adding a semicolon fixes the problem of paragraph text not showing. See also issue #240 .

This issue is for the mdss package (that I maintain), not this one. I don't think the problem is the missing semicolon (the CSS is syntaxically OK), but the lazy loading of fonts in the print preview of Chromium browsers. It is a known issue that fonts only show up on the second rendering in the print preview dialog if they were loaded from a CDN.

**Comment by Haenkos** [comment]
Ah, okay my bad. I'm still pretty inexperienced. Putting a semicolon at the mentioned place did make some black paragraph text show up so i thought i had found something  there. :-)

**Comment by vimtaai** [comment]
@Haenkos No problem 🙂 Your problem was probably solved by reloading the print preview rather than the added semicolon.

As for the comment I think it can stay. 🙂

**Comment by yzane** [comment]
Online (`https://`) stylesheets in `markdown-pdf.styles` have been supported since v1.0.1 — such URLs are emitted as `<link rel="stylesheet">` and applied to the output.

The later comments describe a separate PDF font-loading problem: the mdss maintainer attributed it to Chromium lazily loading CDN-hosted `@font-face` resources during print. If those fonts still do not appear, inline the CSS and fonts, or use locally downloaded CSS and font files. This does not mean the remote stylesheet URL itself is unsupported.

Closing the original online-stylesheet support request as completed. If the stylesheet rules themselves are not applied on the latest version, please leave a comment and we'll reopen.
